### ISSUE TITLE
Feature Request: Support repositories added through Helm CLI

### ISSUE THREAD

**Issue by dbluxo** [belitre/helm-push-artifactory-plugin#1]
Hello @miguel-santiago 

Thank you for writing this Plugin!

From your README.md: 

> This plugin doesn't use repositories added through Helm CLI, in Artifactory those are virtual repositories. To push a chart we need to use a local repository URL

Local Aritfactory repositories can also be added via Helm CLI (Ok, you can't really use them).

But could you add an support to use them for pushing Helm charts into Artifactory?

Instead of:
`$ helm push-artifactory /my/chart/folder https://my-artifactory/my-local-repo --username username --password password`

This:
`$ helm push-artifactory /my/chart/folder added-local-repo-name`

Advantage: You does not always have to enter the credentials and the repo URL.

**Comment by miguel-santiago** [comment]
Hi @dbluxo 

Sorry I didn't see this before!

Sure I can add support for that, I thought about that when I did the plugin and I've been thinking about adding it since then... so, now is the moment!

I'll try to find some time to do it in the next days 😄 

Thank you for using the plugin, and if you have any more ideas please just let me know!

**Comment by miguel-santiago** [comment]
Hi @dbluxo

You should be able to use local repositories added with helm with the version 0.2.0

Let me know if you have any problem!

Cheers.
