### ISSUE TITLE
Helm 3 support

### ISSUE THREAD

**Issue by Xaseron** [belitre/helm-push-artifactory-plugin#5]
We've tried this plugin in a container with Helm 3 beta.3 and if fails if we try to push a chart.
It looks like the paths have changed and it the plugin is looking at the wrong place for the repository configuration. 
This problem occurs if we reference a repository by name, not when we specify the url.
```
# helm version
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```
```
# helm plugin list
NAME            	VERSION	DESCRIPTION                    
push-artifactory	0.3.0  	Push helm charts to artifactory
```
We have set the environment variables in Dockerfile:
```bash
# Jenkins overwrites the HOME environment variable this to make sure the push-artifactory pluigin is found inside the container
ENV XDG_DATA_HOME /
ENV XDG_CONFIG_HOME /
```

This results in the following Helm paths:
```
# helm env
HELM_DEBUG="false" 
HELM_HOME="/helm" 
HELM_PATH_STARTER="/helm/starters" 
HELM_PLUGIN="/helm/plugins" 
HELM_REGISTRY_CONFIG="/helm/registry.json" 
HELM_REPOSITORY_CACHE="/root/.cache/helm/repository" 
HELM_REPOSITORY_CONFIG="/helm/repositories.yaml" 
```
The resulting error in the push process. The plugin should look for the file configured in `HELM_REPOSITORY_CONFIG`.
```
$ helm push-artifactory foo.tar.gz myfancyrepo
Error: Couldn't load repositories file (/helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)
Error: plugin "push-artifactory" exited with error
```

**Comment by belitre** [comment]
Hello @Xaseron and thank you for using the plugin! :)

I'll try to find some free time to fix this and maybe release a version for helm3, hope it will be in the next days!

**Comment by belitre** [comment]
Hi @Xaseron,

I prepared a release that should work with helm 3-beta.3: https://github.com/belitre/helm-push-artifactory-plugin/releases/tag/v1.0.0

Now the plugin will use `HELM_REPOSITORY_CONFIG` if set, or the default repositories file if the variable is not set.

Also, since Helm 3 is still in beta I won't merge the branch to master yet, so to install the plugin you need to add the version if you are installing with `helm plugin install`:

```
helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.0
```

I couldn't do all the tests I wanted, I don't have an artifactory available and I've been testing with a local one with docker, but since all the changes were basically in the part dealing with helm settings and the charts I don't expect any problems. Anyway please let me now if you have any problem and I'll try to fix it as soon as possible.

Cheers!

**Comment by belitre** [comment]
Had to reopen, I didn't test the release in Linux and looks like there are some problems, will work right now on fixing it :)

**Comment by belitre** [comment]
Ok, now everything should be ok, again please remember to install the plugin with:
```
helm plugin install https://github.com/belitre/helm-push-artifactory-plugin --version v1.0.0
```

:)

**Comment by Xaseron** [comment]
Thank you for time, this helped us a lot 🥇

**Comment by deitmerit** [comment]
Helm 3 has been released 4 month ago, maybe it's time to merge this to master? At least mention it in the installation instructions...

**Comment by belitre** [comment]
Hi @deitmerit,

You are totally right, but I won't merge this changes to master, basically I don't want people who has been using the plugin from the beginning and is still using helm 2 to break their CI/CD (though.... yeah, people should move to helm 3).

And yes, I should have a mention in the installation instructions, but I didn't had to make a new release since long time ago, there is a new issue that I'll try to fix in the next days and I'll update the installation instructions for helm 3 users.

Thank you very much!
