### ISSUE TITLE
Update to latest version when install

### ISSUE THREAD

**Issue by ehernandez-xk** [belitre/helm-push-artifactory-plugin#9]
Hello

It is the first time I use this plugin. I spent some time trying to figure out an error when push-artifactory

```
$ helm push-artifactory hello-world-0.1.0.tgz my-local-repo
Error: no repo named "my-local-repo" found
Error: plugin "push-artifactory" exited with error
```

When you installed (the first time) without the plugin version it installs the version described in `plugin.yaml`

```
$ helm plugin install https://github.com/belitre/helm-push-artifactory-plugin
Downloading and installing helm-push-artifactory v0.4.0 ...
```

Then I uninstalled and installed again, Now pointing to the latest version `1.0.0` and it worked (yay)

Also, a weird thing is I tried to reproduce without the version but now install the latest

**Comment by ehernandez-xk** [comment]
When you install without a version it goes to the master branch

**Comment by belitre** [comment]
Hi @ehernandez-xk ,

**The problem:** Helm 3 is already released, but I'm sure there's still a lot of people using helm 2. If I merge right now version `1.0.0`(which is required to make `helm plugin update` to update the version `0.4.0` to `1.0.0` correctly) I'll break for sure more than one pipeline (it already happened once when I merged a branch with a bug, and since almost everyone installs the plugin without a specific version... the pipelines got the last version from master, the version was not working.... and they started to fail on a Saturday night!)

**My advice:** Always use the version flag when installing helm, the plugin or whatever part you use for your CI/CD (or even local) system, so in this case if you are using helm 3 use `--version v1.0.0`, maybe the guys from helm will change the files where they store the config for repos in helm `v3.1.0` again! 😄  

And yes, I know there is a weird behaviour when you specify the version, I'll try to explain a bit why:
When you run `helm plugin install`, helm is really doing a `git clone` of the plugin repo. So if you don't have the plugin installed before it clones using the default branch (`master` in this case). And once it has the repository in the local machine it reads the `plugin.yaml` file and runs the script to install. When you use the flag `--version` helm will clone the branch/tag with the name passed with the flag.

But if you already had the plugin before (even if you uninstalled the plugin, I don't think helm removes the cloned repo properly) then helm just updates that repo (hence, if you got `v1.0.0` before it will keep using that one, and it will keep just updating that branch/tag).

So, as long as you merge every new version to the default branch, and you install the plugin with `helm plugin install` without the `--version` flag, you can keep using `helm plugin update` and it will update the plugin correctly, but as I said I'm a bit scared of merging the last version to master right now :)

Cheers!
